name: TestPost

on:
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Post X(Twitter)
        run: python test.py
